persion:
  name: losy
  age: ${random.int}
  email: foo@gmail.com
  happy: true
  birth: 2021/11/10
  maps:
    k1: v1
    k2: v2
  lists:
    - code
    - music
  dog:
    name: 旺财
    age: 3
dog:
  name: 旺财
  age: 3

spring:
  profiles:
    active: dev

---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: dev
---
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: test